invitations/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^newuser/$', views.new_user, name="new_user"),
    url(r'^$', views.events, name="events"),
    url(r'^filter/(?P<filter>\w+)', views.events, name="events"),
    url(r'^details/(?P<id>\d+)', views.detail, name="detail"),
    url(r'^create/$', views.create, name="create"),
]

invite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from invite.custom import login
from django.contrib.auth.views import logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'^', include('invitations.urls', namespace='invitations')),
]

invitations/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models


class Contact(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Add custom fields here to attach to django User object

    def __unicode__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)


class Event(models.Model):
    title = models.CharField(max_length=100, blank=False)
    host = models.ForeignKey(User)
    description = models.TextField(blank=True)
    date = models.DateTimeField(blank=False)
    location = models.CharField(max_length=100, blank=False)
    min_guests = models.IntegerField(blank=True, default=0)
    max_guests = models.IntegerField(blank=True, default=0)
    deadline = models.DateTimeField(blank=True, null=True)

    def __unicode__(self):
        return self.title


class Invitation(models.Model):
    choices = (
        ('pending', 'Pending'),
        ('going', 'Going'),
        ('declined', 'Declined'),
    )
    event = models.ForeignKey(Event)
    contact = models.ForeignKey(User)
    status = models.CharField(max_length=50, choices=choices, default='pending')

    def __unicode__(self):
        return '%s %s is invited to %s' % (self.contact.first_name, self.contact.last_name, self.event.title)

invitations/forms.py
from django import forms
from invitations.models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'location', 'min_guests', 'date', 'deadline']

invitations/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings
from invite.custom import access_denied
from invitations import models
from invitations.forms import EventForm
from invitations.functions import *


@login_required
def new_user(request):
    u = User.objects.get(id=request.user.id)

    if not u.contact:
        # Hook this user up to our extended User model
        # new_contact = models.Contact()
        pass

    return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)


@login_required
def events(request, filter=None):
    user = User.objects.get(username=request.user)
    nowdate = timezone.now().strftime("%Y-%m-%d 00:00:00+00:00")

    filters = [
        'going',
        'pending',
        'declined',
        'past',
        'hosting',
    ]

    kwargs = {
        'contact': user,
    }

    if not filter or filter == 'going':
        kwargs['event__date__gte'] = nowdate
        kwargs['status'] = 'going'
    elif filter == 'pending':
        kwargs['event__date__gte'] = nowdate
        kwargs['status'] = 'pending'
    elif filter == 'declined':
        kwargs['event__date__gte'] = nowdate
        kwargs['status'] = 'declined'
    elif filter == 'past':
        kwargs['event__date__lt'] = nowdate
    elif filter == 'hosting':
        kwargs['event__date__gte'] = nowdate
        kwargs['event__host__id'] = user.id

    invites = models.Invitation.objects.filter(**kwargs)

    context = {
        'contact': user,
        'invitations': invites,
    }

    return render(request, 'invitations/invite.html', context)


@login_required
def detail(request, id):
    # Redirect if the Event doesn't exist.
    # This basically happens when someone changes the URL manually
    try:
        event = models.Event.objects.get(id=id)
    except ObjectDoesNotExist:
        access_denied()

    # Get the Invitation details for the selected
    # Event that you are invited to
    invitations = models.Invitation.objects.filter(
        event__id=id,
    )

    if not invitations:
        # You are not on the invite list for this event
        # OR the event ID does not exist. Nice try.
        return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)

    going = []
    pending = []

    for invitation in invitations:
        if invitation.status == 'going':
            going.append(invitation)
        elif invitation.status == 'pending':
            pending.append(invitation)

    context = {
        'event': event,
        'going': going,
        'pending': pending,
    }

    return render(request, 'invitations/detail.html', context)


@login_required
def create(request):
    context = {}

    if request.method == 'POST':
        # A POST request; the submitted form
        form = EventForm(request.POST)
        if form.is_valid():
            # Save the newly created Event with Host set to the current user
            event = form.save(commit=False)
            event.host = request.user
            event.save()

            data = qdict_to_dict(form.data)

            # Create the Invitations for this event from the list of people invited.
            for contact in data['invited']:
                # Load the User object for this contact to attach to the Invitation
                this_user = models.User.objects.get(id=contact)
                invitation = models.Invitation(
                    event=event,
                    contact=this_user,
                    status='pending',
                )

                invitation.save()

            return HttpResponseRedirect(reverse('invitations:detail', kwargs={'id': event.pk}))
    else:
        # Only get users that have signed in through the app (contact is not null).
        # This will exclude things like the django admin and other auxiliary users
        # that should not be in the list.
        users = User.objects.filter(is_active=True, contact__isnull=False)
        context['users'] = users

        form = EventForm()

    context['form'] = form

    return render(request, 'invitations/create.html', context)

templates/invitations/base.html
<!doctype html>

{% load staticfiles %}

<html class="no-js" lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Invitations{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/foundation.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>
<body>
    {% if user and user.is_authenticated %}
        <p>Hello, {{ user.first_name }} {{ user.last_name }}</p>
    {% endif %}

    {% block body %}
    {% endblock %}
    <!-- navigation -->
    {% if user.is_authenticated %}
    <nav class="fixednav">
        <ul>
            <li>
                <a href="{% url 'invitations:events' %}">
                    Events<br/>
                    <i class="fa fa-envelope-o" aria-hidden="true"></i>
                </a>
            </li>
            <li>
                <a href="{% url 'invitations:create' %}">
                    Create<br/>
                    <i class="fa fa-plus" aria-hidden="true"></i>
                </a>
            </li>
            <li>
                <a href="{% url 'logout' %}?next={% url 'login' %}">
                    Logout<br/>
                    <i class="fa fa-close" aria-hidden="true"></i>
                </a>
            </li>
            <li>
                <a href="#">
                    Settings<br/>
                    <i class="fa fa-cog" aria-hidden="true"></i>
                </a>
            </li>
        </ul>
    </nav>
    {% endif %}
</body>
<script src="{% static 'js/vendor/jquery.js' %}"></script>
<script src="{% static 'js/vendor/what-input.js' %}"></script>
<script src="{% static 'js/vendor/foundation.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
</html>

templates/invitations/create.html
{% extends 'invitations/base.html' %}

{% load staticfiles %}

{% block title %}
    Create
{% endblock %}

{% block body %}

<!-- page heading -->
<header class="row column">
    <h1>Create an invitation</h1>
</header>

<form action="" method="post" class="createform">
	<div class="row column">
        {% if form.errors %}
            <p>
            Please correct the error{{ form.errors|pluralize }} below.
            </p>
        {% endif %}

        {{ form.title.errors }}
		<label>Title:
			{{ form.title }}
		</label>

        {{ form.description.errors }}
		<label>Describe the event:
            {{ form.description }}
		</label>

        {{ form.location.errors }}
		<label>Location:
			{{ form.location }}
		</label>

        {{ form.min_guests.errors }}
		<label>Minimum # guests:
			{{ form.min_guests }}
		</label>

        {{ form.date.errors }}
		<label>When:
			{{ form.date }}
		</label>

        <!--
		<label>Time:
			<input type="time" placeholder="Start time">
		</label>
		-->

       {% comment %}
        {{ form.deadline.errors }}
		<label>RSVP deadline:
			{{ form.deadline }}
		</label>
        {% endcomment %}

        <h2>People to invite:</h2>
        {% for user in users %}
            <label><input type="checkbox" name="invited" value="{{ user.id }}" class="invitecheck"> {{ user.first_name }} {{ user.last_name }}</label>
        {% endfor %}

        {% csrf_token %}
		<button type="submit" class="button expanded">Continue</button>
	</div>
</form>

{% endblock %}

templates/invitations/detail.html
{% extends 'invitations/base.html' %}

{% load staticfiles %}

{% block title %}
    Details
{% endblock %}

{% block body %}
    <header class="row column">
        <h1>Details</h1>
        <div class="respondbydate">Respond by: {{ event.deadline }}</div>
    </header>

    <div class="row">
        <div class="small-3 columns">Title: </div>
        <div class="small-9 columns">{{ event.title }}</div>
    </div>
    <div class="row">
        <div class="small-3 columns">Description: </div>
        <div class="small-9 columns">{{ event.description }}</div>
    </div>
    <div class="row">
        <div class="small-3 columns">Location: </div>
        <div class="small-9 columns">{{ event.location }}</div>
    </div>
    <div class="row">
        <div class="small-3 columns">Date: </div>
        <div class="small-9 columns">{{ event.date }}</div>
    </div>
    <div class="row column text-center">
        <button class="button primary">I'm going</button> <button class="button secondary">Not going</button>
    </div>
    <div class="row column">
        <ul class="guestmugshots">
            <h3>Going</h3>
            {% if going %}
                {% for g in going %}
                    <li><img src="http://placehold.it/65x65" title="{{ g.contact.first_name }} {{ g.contact.last_name }}" /></li>
                {% endfor %}
            {% else %}
                <li>Nobody is going.</li>
            {% endif %}
        </ul>
    </div>
    <div class="row column">
        <ul class="guestmugshots">
            <h3>Invited</h3>
            {% if pending %}
                {% for p in pending %}
                    <li><img src="http://placehold.it/65x65" title="{{ p.contact.first_name }} {{ p.contact.last_name }}" /></li>
                {% endfor %}
            {% else %}
                <li>Everybody has RSVP'd.</li>
            {% endif %}
        </ul>
    </div>
{% endblock %}

templates/invitations/invite.html
{% extends 'invitations/base.html' %}

{% load staticfiles %}

{% block title %}
    Invitations
{% endblock %}

{% block body %}
    <!-- page heading -->
    <header class="row column">
        <h1>Invitations</h1>
    </header>

    <!-- event status -->
    <section class="row column eventstatus">
        <a href="{% url 'invitations:events' %}">Going <span class="badge">3</span></a> |
        <a href="{% url 'invitations:events' 'pending' %}">Pending <span class="badge">3</span></a> |
        <a href="{% url 'invitations:events' 'declined' %}">Declined <span class="badge">3</span></a> |
        <a href="{% url 'invitations:events' 'past' %}">Past <span class="badge">3</span></a> |
        <a href="{% url 'invitations:events' 'hosting' %}">Hosting <span class="badge">3</span></a>
    </section>

    <!-- invite item -->
    {% if invitations %}
        {% for invitation in invitations %}
        <section class="row itemcontainer">
            <a href="{% url 'invitations:detail' invitation.event.id %}">
                <div class="small-3 columns itemmugshot"><img src="http://placehold.it/125x125" alt="mugshot"></div>
                <div class="small-4 columns itemdescription">
                    <div class="itemtitle">
                        {{ invitation.event.title }}
                    </div>
                    <div class="itemhost">
                        Hosted by {{ invitation.event.host.first_name }} {{ invitation.event.host.last_name }}
                    </div>
                </div>
                <div class="small-3 columns itemwhen">
                    <div class="itemdate">{{ invitation.event.date }}</div>
                    <div class="itemtime">{{ invitation.event.time }}</div>
                </div>
                <div class="small-2 columns itemsspotsopen">0/{{ invitation.event.min_guests }}</div>
            </a>
        </section>
        {% endfor %}
    {% else %}
        <section class="row itemcontainer">
        Nothing to show.
        </section>
    {% endif %}
{% endblock %}

templates/invitations/login.html
{% extends 'invitations/base.html' %}

{% load staticfiles %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <div class="row">
        <div class="medium-6 medium-centered large-4 large-centered columns">
            <form action="{% url 'invitations:events' 'pending' %}" method="post">
                {% csrf_token %}
                <div class="row column log-in-form">
                    <p class="text-center"><img class="circle" src="http://placehold.it/150x150" alt=""></p>
                    <label>Email
                        <input type="text" name="email" placeholder="somebody@example.com">
                    </label>
                    <label>Password
                        <input type="password" name="password" placeholder="Password">
                    </label>
                    <p><button type="submit" class="button expanded">Log In</button></p>
                    <!-- <p class="text-center"><a href="#">Forgot your password?</a></p>    -->
                </div>
            </form>
        </div>
    </div>
{% endblock %}